language: bash

sudo: required

services:
  - docker

script:
  - docker build -t spark-tk .
  - docker run spark-tk

after_success:
  - echo "Travis build succeeded"

after_failure:
  - echo "Travis build failed"
